import util from 'util';
import { downloadMediaMessage } from 'baileys';

export default {
    command: 'run',
    alias: ['runcode', 'runc', 'execfile'],
    help: '`<reply doc>`',
    description: 'Jalankan kode JavaScript dari reply teks atau file.',
    onlyOwner: true,
    typing: true,

    async execute(m, sock) {
        if (!m.quoted) return m.reply('Reply pesan berisi kode atau file dulu!');

        let code = '';
        const q = m.quoted;

        if (q.isMedia) {
            try {
                const buffer = await downloadMediaMessage(
                    {
                        key: q.key,
                        message: { [q.type]: q.msg }
                    },
                    'buffer',
                    {},
                    { logger: console }
                );
                code = buffer.toString('utf-8').replace(/^\uFEFF/, '').trim();
            } catch (err) {
                return m.reply(`❌ Gagal download file: ${err.message}`);
            }
        } else {
            code = q.text;
        }

        if (!code) return m.reply('❌ Tidak ada kode ditemukan.');

        const consoleOutput = [];
        const originalConsoleLog = console.log;
        console.log = (...args) => {
            const str = args.map(arg => typeof arg === 'object' ? util.inspect(arg, { depth: 2 }) : String(arg)).join(' ');
            consoleOutput.push(str);
            originalConsoleLog(...args);
        };

        try {
            let wrappedCode = code;
            const trimmedCode = code.trim();

            // Cek apakah kode adalah ekspresi sederhana satu baris
            const isSimpleExpression = !trimmedCode.includes('\n') && 
                                     !trimmedCode.includes(';') && 
                                     !/^(const|let|var|function|class|async|await|for|if|switch|try|while|return)/.test(trimmedCode);

            // Cek apakah kode mengandung komentar "generated by" atau sudah terlihat seperti script utuh
            const isFullScript = trimmedCode.includes('await sock.') || trimmedCode.includes('sock.relayMessage');

            if (isSimpleExpression) {
                wrappedCode = `return (${trimmedCode});`;
            } else if (!isFullScript) {
                // Hanya bungkus return jika baris terakhir bukan blok kode atau script utuh
                const lines = trimmedCode.split('\n');
                const lastLine = lines[lines.length - 1].trim();
                if (lastLine && !lastLine.endsWith(';') && !lastLine.endsWith('}') && !lastLine.startsWith('return') && !/^(break|continue|throw|if|for|while|switch|const|let|var|class)/.test(lastLine)) {
                    lines[lines.length - 1] = `return (${lastLine});`;
                    wrappedCode = lines.join('\n');
                }
            }

            const asyncFunc = new Function('ctx', `
                const { m, sock, quoted, console, process, Buffer, util } = ctx;
                const jid = m.chat; 
                const sender = m.sender;
                return (async () => { 
                    try {
                        ${wrappedCode} 
                    } catch (e) {
                        throw e;
                    }
                })();
            `);

            const evaled = await asyncFunc({ m, sock, quoted: q, console, process, Buffer, util });
            
            console.log = originalConsoleLog; 

            let result = '';
            if (consoleOutput.length > 0) result += `📜 *Console:*\n${consoleOutput.join('\n')}\n\n`;
            
            if (evaled !== undefined) {
                result += typeof evaled !== 'string' ? util.inspect(evaled, { depth: 2 }) : evaled;
            }

            if (!result && consoleOutput.length === 0) result = 'Selesai (No Output)';

            await sock.sendMessage(m.chat, { text: result.slice(0, 4000) }, { quoted: m });

        } catch (err) {
            console.log = originalConsoleLog;
            await m.reply(`❌ *Error Executing Code*:\n\`\`\`js\n${err.message || err}\n\`\`\``);
        }
    }
};