import crypto from 'crypto';
import { generateWAMessageFromContent } from 'baileys';

import config from '../../settings.js';
import { getThumb, listThumbs } from '../../database/db_thumbnails.js';

export default {
    command: 'cekthumb',
    alias: ['viewthumb', 'lihatthumb', 'viewthumbnail', 'cekthumbnail', 'lihatthumbnail'],
    description: 'Melihat pratinjau thumbnail + opsional favicon',
    help: '`<nama> , <icon>`',
    onlyOwner: true,
    typing: true,

    async execute(m, sock, args) {
        if (args.length === 0) {
            const allItems = listThumbs();
            if (allItems.length === 0) {
                return await m.reply('❌ Database thumbnail masih kosong.');
            }

            let listMsg = `*DAFTAR THUMBNAIL & FAVICON*\n\n`;
            allItems.forEach((item, i) => {
                listMsg += `${i + 1}. ${item.name}\n`;
            });
            listMsg += `\n\nCara penggunaan:\n`;
            listMsg += `• ${m.prefix}cekthumb nama_thumb\n`;
            listMsg += `• ${m.prefix}cekthumb nama_thumb, nama_favicon`;
            return await m.reply(listMsg);
        }

        const fullInput = args.join(' ').trim();
        const parts = fullInput.split(',').map(p => p.trim().toLowerCase());

        const thumbName = parts[0];
        const faviconName = parts[1] || null;

        if (!thumbName) {
            return await m.reply('❌ Masukkan nama thumbnail!');
        }

        const thumbData = getThumb(thumbName);
        if (!thumbData) {
            return await m.reply(`❌ Thumbnail *"${thumbName}"* tidak ditemukan.`);
        }

        let faviconData = null;
        if (faviconName) {
            const fav = getThumb(faviconName);
            if (!fav || fav.type !== 'favicon' || !fav.faviconMMSMetadata) {
                return await m.reply(`❌ Favicon *"${faviconName}"* tidak ditemukan atau bukan tipe favicon.`);
            }
            faviconData = fav.faviconMMSMetadata;
        }

        try {
            const targetUrl = 'https://chat.whatsapp.com';

            const extendedText = {
                text: `${targetUrl}\nPreview: ${thumbName}${faviconName ? ` + ${faviconName}` : ''}`,
                matchedText: targetUrl,
                description: "Custom Thumbnail dari Database",
                title: `Result: ${thumbName}`,
                previewType: 1,
                inviteLinkGroupTypeV2: 0,
                ...thumbData
            };

            if (faviconData) {
                extendedText.faviconMMSMetadata = faviconData;
            }

            const content = { extendedTextMessage: extendedText };

            await sock.relayMessage(m.chat, content, { quoted: m });

            // Fungsi toCode untuk generate kode yang rapi
            function escapeString(str) {
                return str.replace(/\\/g, '\\\\')
                         .replace(/\n/g, '\\n')
                         .replace(/\r/g, '\\r')
                         .replace(/\t/g, '\\t')
                         .replace(/"/g, '\\"');
            }

            function isLong(value) {
                return value && typeof value === 'object' && 
                       typeof value.low === 'number' && 
                       typeof value.high === 'number';
            }

            function toCode(value, indentSize = 2, level = 0) {
                const indent = ' '.repeat(indentSize * level);
                const nextIndent = ' '.repeat(indentSize * (level + 1));

                if (value instanceof Uint8Array || Buffer.isBuffer(value)) {
                    return `"${Buffer.from(value).toString('base64')}"`;
                }
                if (isLong(value)) {
                    return String(value.toNumber ? value.toNumber() : value.low);
                }
                if (typeof value === 'string') return `"${escapeString(value)}"`;
                if (typeof value === 'number' || typeof value === 'boolean') return String(value);
                if (value === null) return 'null';
                if (value === undefined) return 'undefined';

                if (Array.isArray(value)) {
                    if (!value.length) return '[]';
                    return `[\n${value.map(v => `${nextIndent}${toCode(v, indentSize, level + 1)}`).join(',\n')}\n${indent}]`;
                }

                if (typeof value === 'object') {
                    const entries = Object.entries(value);
                    if (!entries.length) return '{}';
                    return `{\n${entries.map(([k, v]) => 
                        `${nextIndent}${k}: ${toCode(v, indentSize, level + 1)}`
                    ).join(',\n')}\n${indent}}`;
                }

                return String(value);
            }

            const rawCode = `/*
  Generated By ${config.botName}
  Date: ${new Date().toLocaleString('id-ID')}
  Thumbnail : ${thumbName}
  Favicon   : ${faviconName || 'Tidak digunakan'}
*/

const content = ${toCode(content)}

const relayOption = {}

await sock.relayMessage(jid, content, relayOption)`;

            const randomID = crypto.randomBytes(3).toString('hex');

            await sock.sendMessage(m.chat, {
                document: Buffer.from(rawCode),
                mimetype: 'application/javascript',
                fileName: `${thumbName}${faviconName ? '_with_' + faviconName : ''}_${randomID}.js`,
                caption: `✅ *Preview berhasil dibuat*\n\n• Thumbnail : *${thumbName}*\n• Favicon   : *${faviconName || '-'}*`
            }, { quoted: m });

        } catch (err) {
            console.error(err);
            await m.reply('❌ Gagal menampilkan preview.');
        }
    }
};